// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtP_-bQ5GiKQnfBhaaRh4mg59HKmf1OLg',
    appId: '1:665117309588:web:bf6d99fa1e04c269b99281',
    messagingSenderId: '665117309588',
    projectId: 'hack-team-grey-matter-gurus',
    authDomain: 'hack-team-grey-matter-gurus.firebaseapp.com',
    storageBucket: 'hack-team-grey-matter-gurus.appspot.com',
    measurementId: 'G-XSRR41V2PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLdqoTitE57Bam3ORLu5z3hkRX3_iYe3c',
    appId: '1:665117309588:android:1dc6c8418887c828b99281',
    messagingSenderId: '665117309588',
    projectId: 'hack-team-grey-matter-gurus',
    storageBucket: 'hack-team-grey-matter-gurus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc9S8Xv4fDi4bhTdSzZK8amS28curalGw',
    appId: '1:665117309588:ios:032523526181935cb99281',
    messagingSenderId: '665117309588',
    projectId: 'hack-team-grey-matter-gurus',
    storageBucket: 'hack-team-grey-matter-gurus.appspot.com',
    iosBundleId: 'com.example.weCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc9S8Xv4fDi4bhTdSzZK8amS28curalGw',
    appId: '1:665117309588:ios:032523526181935cb99281',
    messagingSenderId: '665117309588',
    projectId: 'hack-team-grey-matter-gurus',
    storageBucket: 'hack-team-grey-matter-gurus.appspot.com',
    iosBundleId: 'com.example.weCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtP_-bQ5GiKQnfBhaaRh4mg59HKmf1OLg',
    appId: '1:665117309588:web:f6be0392fb16ac31b99281',
    messagingSenderId: '665117309588',
    projectId: 'hack-team-grey-matter-gurus',
    authDomain: 'hack-team-grey-matter-gurus.firebaseapp.com',
    storageBucket: 'hack-team-grey-matter-gurus.appspot.com',
    measurementId: 'G-9LJJGF5ZY0',
  );

}